config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes do
    resources :doses, only: %w[new create destroy], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :recipes, through: :doses
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :doses, dependent: :destroy, inverse_of: :recipe
  has_many :ingredients, through: :doses

   accepts_nested_attributes_for :doses,
                                reject_if: proc { |attributes| attributes[:type_dose].blank? },
                                allow_destroy: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :time_prep, :difficulty ],
    associated_against: {
      ingredients: [ :name, :category ]
    },
    using: {
      tsearch: { prefix: true }
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!
end

app/controllers/doses_controller.rb
# class DosesController < ApplicationController
#   def new
#     @dose = Dose.new
#   end

#   def create
#     @dose = Dose.create!(params_dose)
#   end

#   def destroy
#     @dose = Dose.find(params[:id])
#     @dose.destroy
#     redirect_to recipe_path(@dose.recipe)
#   end

#   private

#   def params_dose
#     params.require(:dose).permit(:type_dose, :number, :ingredient_id, :recipe_id)
#   end
# end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe ,only: %i[show edit update destroy]

  def index
    @recipes = Recipe.all

    if params[:query].present?
      @recipes = @recipes.global_search(params[:query])
    else
      @recipes = Recipe.all
    end
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params_recipe)
    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
  end

  def update
    @recipe.update_atributes(params_recipe)
    if @recipe.save
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
  def params_recipe
    params.require(:recipe).permit(:name, :desc, :time_prep, :difficulty, doses_attributes: [:id, :type_dose, :number, :ingredient_id, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/recipes/_dose_fields.html.erb
<div class="nested-fields">
  <%= f.input :type_dose %>
  <%= f.input :number %>
  <%= f.association :ingredient %>
  <%= link_to_remove_association "retirer cet ingrédient", f %>
</div>

app/views/recipes/_doses_field.html.erb
<div class="nested-fields">
  <%= f.input :type_dose %>
  <%= f.input :number %>
  <%= f.association :ingredient %>
  <%= link_to_remove_association "retirer cet ingrédient", f %>
</div>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

app/views/recipes/index.html.erb
<header class='hero'>
  <section class="jumbotron">
    <div class="container mastinfo">
      <div class="display-4">Trouver une recette ou un idée</div>
      <div class="text-center">
          <%= form_tag recipes_path, method: :get do %>
            <div class="d-flex justify-content-center align-items-center" style="position: relative;">
              <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Recette, ingrédient...",
              autocomplete:"off"
              %>
              <%= button_tag type: 'submit', class: "bg-grey p-1 text-warning loupe" do %>
                <i class="fa fa-search" aria-hidden="true"></i>
              <% end %>
            </div>
          <% end %>
        </div>
    </div>
  </section>
</header>

<main>
<section>
    <div class="container">
      <div class="row">
      </div>
      <br>
      <div class="row bg-light p-3">
        <% @recipes.each do |recipe| %>
          <div class="col">
            <div class="card rounded">
              <%# <img src="http://lorempixel.com/1000/500" alt="" class="card-img-top"> %>
              <div class="card-body">
                <h4 class="card-title"><%= recipe.name %></h4>
                <p class="card-text"><%= recipe.desc %></p>
                <%= link_to "Get it!", recipe_path(recipe), class:"btn btn-success" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</main>

app/views/recipes/new.html.erb
<h1>New Project</h1>
<%= simple_form_for @recipe do |f| %>
  Nom de la recette: <%= f.text_field :name %>
  Temps de préparation: <%= f.text_field :time_prep %>
  Difficulté: <%= f.text_field :difficulty %>
  <h3>Tasks</h3>
  <div id='tasks'>
    <%= f.simple_fields_for :doses, Dose.new do |dose| %>
      <%= render 'dose_fields', f: dose %>
    <div class='links'>
      <%= link_to_add_association 'add task', f, :doses,
    partial: 'dose_fields' %>
    </div>
    <% end %>
  </div>
  <%= f.submit 'Save' %>
<% end %>

app/views/recipes/show.html.erb
<div class="container mt-5">
  <div class="card bg-light my-2 mx-2 p-5">
    <div class="d-flex justify-content-between">
      <div class="flex-grow-1 ">
        <div class="text-center border-bottom mb-3">
          <h2><%= @recipe.name %></h2>
        </div>
        <% @recipe.doses.each do |dose| %>
    <div class="d-flex justify-content-between mt-4 border-bottom ">
          <p><%= dose.type_dose %> </p>
          <p><%= dose.ingredient.name %> </p>
            <i> <%= link_to "delete", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %> </i>
    </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="social">
      <a href=""><i class="fab fa-facebook fa-2x"></i></a>
      <a href=""><i class="fab fa-twitter fa-2x"></i></a>
      <a href=""><i class="fab fa-youtube fa-2x"></i></a>
      <a href=""><i class="fab fa-linkedin fa-2x"></i></a>
    </div>
    <p>Copyright &copy; 2020 - My cookbook</p>
  </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://i.pinimg.com/originals/c8/7c/ff/c87cffd20a28efb1b6a3681c43ceab90.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Ajouter une recette", new_recipe_path, class:"nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>